spring:
  application:
    name: helloworld
  rainbow:
    refreshScope: false
server:
  port: 8199
trpc:
  #全局配置
  global:
    namespace: Development  #环境类型，分正式环境和非正式环境两种类型
  #  env_name: test   #环境名称，非正式环境下多环境的名称
  #服务端配置
  server:
    app: trpc_java #业务的应用名
    server: trpc_java_demo #业务的服务名
    local_ip: 127.0.0.1   #本地IP，容器内为容器ip，物理机或虚拟机为本机ip
    #  jvm_params: -Xms1024m  -Xmx1024m  -Xmn512m  -XX:+UseG1GC  #配置jvm相关参数
    jvm_params: -Xms1024m   -Xmx1024m  -Xmn512m
    filters:
      - limiter_polaris
    service:
      - name: trpc.trpc_java.trpc_java_demo.TestPolarisTRPC
        impls:
          - com.tencent.trpc.demos.limiter.polaris.service.HelloServiceImpl
        port: 8085
        protocol: trpc
        transporter: netty
        serialization: pb
        # trpc-cli -verbose -func /trpc.test.demo.Hello/SayHello -target ip://127.0.0.1:8085 -protocol trpc -body '{"msg":"hello,trpc-cli"}'
      - name: trpc.trpc_java.trpc_java_demo.Async
        impls:
          - com.tencent.trpc.demos.limiter.polaris.service.AsyncServiceImpl
        port: 8086
        protocol: trpc
        transporter: netty
        serialization: pb
        # trpc-cli -verbose -func /trpc.test.demo.Hello/SayHello -target ip://127.0.0.1:8086 -protocol trpc -body '{"msg":"hello,trpc-cli"}'
  client:
    service:
      - name: testPolarisTRPC   # 该name不用作北极星寻址
        interface: com.tencent.trpc.demo.api.HelloAPI
        #      naming_url: polaris://trpc.trpc_java.trpc_java_demo.TestPolarisTRPC
        naming_url: ip://127.0.0.1:8085                         #naming配置,直连 ip://ip:port, 名字服务: polaris://trpc.TestApp.TestServer.Greeter?key=value&key=value  l5://mid:cmid  cmlb://id
        protocol: trpc
        serialization: pb
  plugins:
    registry:
      polaris: #名字注册服务的远程对象
        heartbeat_interval: 3000 #名字注册服务心跳上报间隔
        mode: 0                                      #选填，运行模式0-noagent 1-withagent
        protocol: grpc                               #选填，服务发现的rpc协议，暂时只支持grpc
        register_self: false  # 需要改成true
        service:
          - name: trpc.trpc_java.trpc_java_demo.TestPolarisTRPC
            namespace: Development #环境类型，分正式production和非正式development两种类型
          - name: trpc.trpc_java.trpc_java_demo.Async
            namespace: Development #环境类型，分正式production和非正式development两种类型
    selector:
      polaris:
        mode: 0
        # 以下的配置与polaris java sdk配置一致。
        global:
          system:
            discoverCluster:
              sameAsBuiltin: true
            healthCheckCluster:
              sameAsBuiltin: true
          serverConnector:
            # target server address
            addresses:
              - 127.0.0.1:8091
          statReporter:
            enable: true
            plugin:
              prometheus:
                port: 28082